### ISSUE TITLE
Use HTMLCSSToImage to auto-generate Twitter cards

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/jasonet.co#20]
I want to autogenerate Twitter cards for new posts! I'd like to use [HTMLCSSToImage](https://htmlcsstoimage.com) if possible 👌 getting the fonts just right might be tough, I'd love to use Inter UI if possible but it isn't a Google Font.

This could be in the Gatsby build step, or as a separate GitHub Action - TBD!

cc @mscoutermarsh I'm just using this for everything now 🤷‍♂️

**Comment by mscoutermarsh** [comment]
For Inter UI, if you load it in like any other web font (in HTML). Should work!
