### ISSUE TITLE
Using the `schedule` trigger

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/jasonet.co#35]
I'd like to write a post that focuses on the new `schedule` trigger for GitHub Actions: https://developer.github.com/actions/changes/2019-04-05-scheduling-workflows/

General structure:

* What it is
* Basic cron syntax overview (link to resources like crontab.guru)
* Some use-cases (shared provided permission is granted)
  * `probot/stale-action`
  * `electron/released`
  * `JasonEtco/create-an-issue`

**Comment by johnletey** [comment]
@JasonEtco This sounds amazing!
